# Generated by Django 5.2.4 on 2025-07-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orderbuget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderBuget',
            new_name='OrderBudget',
        ),
    ]
